---
title: 'Describe case data'
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- how to obtain delay distributions from a literature systematic review?
- what is the natural history of the disease?
- how long should contacts be followed?
- what is the required duration of contact tracing?
- how long should cases be isolated to reduce transmission?

- what are the epidemiological characteristics of the infection?
- what is the demographic distribution of cases?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Explain how to use markdown with the new lesson template
- Demonstrate how to include pieces of code, figures, and nested challenge blocks

::::::::::::::::::::::::::::::::::::::::::::::::

## Introduction

This is a lesson created via The Carpentries Workbench. 

# Content

Bla

::::::::::::::::::::::::::::::::::::: keypoints 

- Use `.md` files for episodes when you want static content
- Use `.Rmd` files for episodes when you need to generate output
- Run `sandpaper::check_lesson()` to identify any issues with your lesson
- Run `sandpaper::build_lesson()` to preview your lesson locally

::::::::::::::::::::::::::::::::::::::::::::::::

