---
title: "Week 2: Access delays to estimate transmission and severity"
format: 
  html: default # learners solutions
  docx: default # learners practical
  gfm: default # instructors
keep-md: true
format-links: false
---

::: {.content-hidden when-format="html"}

<!-- visible for instructors only -->
<!-- practical-week.md is generated from practical-week.qmd. Please edit that file -->
<!-- commit .md and .qmd files together -->

:::

Welcome!

A reminder of our Code of Conduct: 
<https://github.com/epiverse-trace/.github/blob/main/CODE_OF_CONDUCT.md>


# Practical

<!-- visible for learners and instructors at practical -->

## Transmission

Estimate $R_{t}$, _new infections_, _new reports_, _growth rate_, and _doubling/halving time_ using the following available inputs:

- Incidence of reported cases per day
- Reporting delay

Instructions, as a group:

- Create one copy of the Posit Cloud project `<paste link>`.
- Solve the challenge using the `Code chunk` as a guide.
- Paste your figure and table outputs.
- **Report** to all the group at the end of the session.

### Inputs

| Group | Incidence | Link |
|---|---|---|
| 1 | COVID 30 days | <https://epiverse-trace.github.io/tutorials-middle/data/covid_30days.rds> |
| 2 | Ebola 35 days | <https://epiverse-trace.github.io/tutorials-middle/data/ebola_35days.rds> |
| 3 | Ebola 60 days | <https://epiverse-trace.github.io/tutorials-middle/data/ebola_60days.rds> |
| 4 | COVID 60 days | <https://epiverse-trace.github.io/tutorials-middle/data/covid_60days.rds> |

| Disease | Reporting delays |
|---|---|
| Ebola | The time difference between symptom onset and case report follows a Lognormal distribution with uncertainty. The **mean** follows a Normal distribution with mean = 4 and sd = 0.5. The **standard deviation** follows a Normal distribution with mean = 1 and sd = 0.5. Bound the distribution with max = 5. |
| COVID | The time difference between symptom onset and case report follows a Gamma distribution with uncertainty. The **mean** follows a Normal distribution with mean = 2 and sd = 0.5. The **standard deviation** follows a Normal distribution with mean = 1 and sd = 0.5. Bound the distribution with a max = 5. |

: {tbl-colwidths="[15,85]"}

### Code chunk

```r
# Load packages
library(epiparameter)
library(EpiNow2)
library(tidyverse)


# Read reported cases
dat <- read_rds("paste/link/url/here") %>%
  dplyr::select(date, confirm)


# Access parameters for delay distributions



# Get maximum value for each distribution



# Extract parameters



# Adapt {epiparameter} to {EpiNow2} distribution interfase



# Set the number of parallel cores
withr::local_options(list(mc.cores = parallel::detectCores() - 1))


# Estimate transmission using EpiNow2::epinow()
# with EpiNow2::*_opts() functions for delays and stan



# Print plot and summary table outputs



```

### Paste outputs. Write your interpretation

Group 1

| output | paste here |
|---|---|
| figure |  |
| table |  |

Reply with your Interpretation and Discussion:

```







```


------------------------

Group 2

| output | paste here |
|---|---|
| figure |  |
| table |  |

Reply with your Interpretation and Discussion:

```







```


------------------------

Group 3

| output | paste here |
|---|---|
| figure |  |
| table |  |

Reply with your Interpretation and Discussion:

```







```


------------------------

Group 4

| output | paste here |
|---|---|
| figure |  |
| table |  |

Reply with your Interpretation and Discussion:

```







```


## Severity




::: {.content-visible unless-format="docx"}

# Solutions

<!-- visible for instructors and learners after practical (solutions) -->

solutions

:::

# end